---
abstract: 'filesystem based personal video hosting'
author:
  - 'Justin Hawkins <justin@eatmorecode.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Video-Host
requires:
  Carp: 0
  Mojolicious: 4.63
  Moose: 2.1005
version: 0.1
